# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Game customer App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'ObjectMapper', '~> 3.1'

  # Pods for Game customer App

  target 'Game customer AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Game customer AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
